name: Publish Sphinx Documentation

on:
  push:
    branches:
      - haoti/doc_update

jobs:
  publish_sphinx_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.1"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install dependencies
        working-directory: docs
        run: |
          uv sync --python 3.10
      - name: Sphinx build
        working-directory: docs
        run: |
          uv run just doc
      - name: Create index.html
        working-directory: docs
        run: |
          uv run python redirect.py ${{ github.ref_name }} > build/index.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          external_repository: Cytnx-dev/Cytnx_doc
          publish_dir: docs/build/
          force_orphan: true
